#!/bin/sh /etc/rc.common
# Copyright (C) 2016 EasyPi Software Foundation

START=99
STOP=1

USE_PROCD=1
PROG=/usr/bin/kcptun
NAME=kcptun
PIDCOUNT=0

validate_section_kcptun()
{
	uci_validate_section kcptun kcptun "${1}" \
		'enabled:bool:0' \
		'localaddr:string' \
		'remoteaddr:string' \
		"key:string:it's a secrect" \
		'extra_params:list(string)'
}

kcptun_instance()
{
	local enabled localaddr remoteaddr key extra_params

	validate_section_kcptun "${1}" || {
		echo "validation failed"
		return 1
	}

	[ "${enabled}" = "0" ] && return 1
	PIDCOUNT="$(( ${PIDCOUNT} + 1))"

	procd_open_instance
	procd_set_param command "${PROG}"
	[ -n "${localaddr}" ] && procd_append_param command --localaddr "${localaddr}"
	[ -n "${remoteaddr}" ] && procd_append_param command --remoteaddr "${remoteaddr}"
	[ -n "${key}" ] && procd_append_param command --key "${key}"
	config_list_foreach "${1}" extra_params append_extra_params
	procd_set_param respawn
	procd_close_instance
}

append_extra_params()
{
	procd_append_param command "--${1}"
}

start_service()
{
	config_load "${NAME}"
	config_foreach kcptun_instance kcptun
}
